# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('cid', models.CharField(db_column='CID', default='', max_length=255, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='COMPANY_NAME', default='', max_length=256)),
                ('perma_link', models.CharField(db_column='PERMA_LINK', default='', max_length=256)),
                ('image', models.CharField(blank=True, db_column='IMAGE', max_length=256, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=6000, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=256, null=True)),
                ('uuid', models.CharField(db_column='UUID', default='', max_length=256)),
                ('total_funding', models.CharField(blank=True, db_column='TOTAL_FUNDING', max_length=256, null=True)),
            ],
            options={
                'db_table': 'COMPANIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VC_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_name', models.CharField(db_column='VC_NAME', default='', max_length=256)),
                ('company_name', models.CharField(db_column='COMPANY_NAME', default='', max_length=256)),
            ],
            options={
                'db_table': 'VC_COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VC_data',
            fields=[
                ('vid', models.CharField(db_column='VID', default='', max_length=255, primary_key=True, serialize=False)),
                ('vc_name', models.CharField(db_column='VC_NAME', default='', max_length=256)),
                ('perma_link', models.CharField(db_column='PERMA_LINK', default='', max_length=256)),
                ('image', models.CharField(blank=True, db_column='IMAGE', max_length=256, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=6000, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=256, null=True)),
                ('uuid', models.CharField(db_column='UUID', default='', max_length=256)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=256, null=True)),
                ('city', models.CharField(blank=True, db_column='CITY', max_length=256, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZIPCODE', max_length=256, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=10, null=True)),
            ],
            options={
                'db_table': 'VCs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VcplatformCompanies',
            fields=[
                ('cid', models.CharField(db_column='CID', max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='COMPANY_NAME', max_length=500)),
                ('perma_link', models.CharField(db_column='PERMA_LINK', max_length=500)),
                ('image', models.CharField(db_column='IMAGE', max_length=500)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=500)),
                ('url', models.CharField(db_column='URL', max_length=500)),
                ('uuid', models.CharField(db_column='UUID', max_length=500)),
                ('total_funding', models.CharField(db_column='TOTAL_FUNDING', max_length=500)),
            ],
            options={
                'db_table': 'vcplatform_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VcplatformVcCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_column='COMPANY_NAME', max_length=500)),
                ('vc_name', models.CharField(db_column='VC_NAME', max_length=500)),
            ],
            options={
                'db_table': 'vcplatform_vc_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VcplatformVcData',
            fields=[
                ('vid', models.CharField(db_column='VID', max_length=10, primary_key=True, serialize=False)),
                ('vc_name', models.CharField(db_column='VC_NAME', max_length=500)),
                ('perma_link', models.CharField(db_column='PERMA_LINK', max_length=500)),
                ('image', models.CharField(db_column='IMAGE', max_length=500)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=500)),
                ('url', models.CharField(db_column='URL', max_length=500)),
                ('uuid', models.CharField(db_column='UUID', max_length=500)),
                ('address', models.CharField(db_column='ADDRESS', max_length=500)),
                ('city', models.CharField(db_column='CITY', max_length=100)),
                ('zipcode', models.CharField(db_column='ZIPCODE', max_length=20)),
                ('state', models.CharField(db_column='STATE', max_length=20)),
            ],
            options={
                'db_table': 'vcplatform_vc_data',
                'managed': False,
            },
        ),
    ]
