# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('CID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('COMPANY_NAME', models.CharField(max_length=500)),
                ('PERMA_LINK', models.CharField(max_length=500)),
                ('IMAGE', models.CharField(max_length=500)),
                ('DESCRIPTION', models.CharField(max_length=500)),
                ('URL', models.CharField(max_length=500)),
                ('UUID', models.CharField(max_length=500)),
                ('TOTAL_FUNDING', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='VC_Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMPANY_NAME', models.CharField(max_length=500)),
                ('VC_NAME', models.CharField(max_length=500)),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcplatform.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='VC_data',
            fields=[
                ('VID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('VC_NAME', models.CharField(max_length=500)),
                ('PERMA_LINK', models.CharField(max_length=500)),
                ('IMAGE', models.CharField(max_length=500)),
                ('DESCRIPTION', models.CharField(max_length=500)),
                ('URL', models.CharField(max_length=500)),
                ('UUID', models.CharField(max_length=500)),
                ('ADDRESS', models.CharField(max_length=500)),
                ('CITY', models.CharField(max_length=100)),
                ('ZIPCODE', models.CharField(max_length=20)),
                ('STATE', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='vc_companies',
            name='VID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcplatform.VC_data'),
        ),
    ]
