# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcplatform', '0002_auto_20170623_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='VC_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_name', models.CharField(db_column='VC_NAME', max_length=256)),
                ('company_name', models.CharField(db_column='COMPANY_NAME', max_length=256)),
            ],
            options={
                'db_table': 'VC_COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VC_data',
            fields=[
                ('vid', models.CharField(db_column='VID', max_length=255, primary_key=True, serialize=False)),
                ('vc_name', models.CharField(db_column='VC_NAME', max_length=256)),
                ('perma_link', models.CharField(db_column='PERMA_LINK', max_length=256)),
                ('image', models.CharField(blank=True, db_column='IMAGE', max_length=256, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=6000, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=256, null=True)),
                ('uuid', models.CharField(db_column='UUID', max_length=256)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=256, null=True)),
                ('city', models.CharField(blank=True, db_column='CITY', max_length=256, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZIPCODE', max_length=256, null=True)),
                ('state', models.CharField(blank=True, db_column='STATE', max_length=10, null=True)),
            ],
            options={
                'db_table': 'VCs',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='companies',
            table='COMPANIES',
        ),
    ]
