# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcplatform', '0005_auto_20170623_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vc_company',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='vc_data',
            options={'managed': True},
        ),
    ]
