# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcplatform', '0006_auto_20170623_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vc_company',
            name='company_name',
            field=models.CharField(db_column='COMPANY_NAME', default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='vc_company',
            name='vc_name',
            field=models.CharField(db_column='VC_NAME', default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='vc_data',
            name='perma_link',
            field=models.CharField(db_column='PERMA_LINK', default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='vc_data',
            name='uuid',
            field=models.CharField(db_column='UUID', default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='vc_data',
            name='vc_name',
            field=models.CharField(db_column='VC_NAME', default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='vc_data',
            name='vid',
            field=models.CharField(db_column='VID', default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
