# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcplatform', '0007_auto_20170623_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vc_company',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vc_data',
            options={'managed': False},
        ),
    ]
